[phases.install]
cmds = ["composer install --no-dev --ignore-platform-reqs --no-scripts --optimize-autoloader"]

[phases.build]
cmds = ["php artisan package:discover --ansi || true", "php artisan config:cache || true", "php artisan route:cache || true", "php artisan view:cache || true"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
