<?php

namespace Database\Seeders;

use App\Models\FormTemplate;
use App\Models\FormTemplateField;
use Illuminate\Database\Seeder;

class JapanFormTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $template = FormTemplate::updateOrCreate(
            ['country' => 'Japan'],
            [
                'name'           => 'Japan Study Abroad Application',
                'intake_options' => ['April 2025', 'October 2025', 'April 2026', 'October 2026'],
                'is_active'      => true,
                'notes'          => 'Standard application form for Japan study programs. Covers language schools, vocational schools, and universities.',
            ]
        );

        // Clear existing and re-seed
        FormTemplateField::where('form_template_id', $template->id)->delete();

        $fields = [

            // ── Personal ─────────────────────────────────────────────────────
            [
                'field_key'          => 'date_of_birth',
                'label'              => 'Date of Birth',
                'section'            => 'personal',
                'field_type'         => 'date',
                'is_required'        => true,
                'requires_document'  => false,
                'placeholder'        => null,
                'helper_text'        => 'Must be between 18–35 years for most Japan programs.',
                'options'            => null,
                'sort_order'         => 1,
            ],
            [
                'field_key'          => 'gender',
                'label'              => 'Gender',
                'section'            => 'personal',
                'field_type'         => 'select',
                'is_required'        => true,
                'requires_document'  => false,
                'placeholder'        => 'Select gender',
                'helper_text'        => null,
                'options'            => ['Male', 'Female', 'Other'],
                'sort_order'         => 2,
            ],
            [
                'field_key'          => 'nationality',
                'label'              => 'Nationality',
                'section'            => 'personal',
                'field_type'         => 'text',
                'is_required'        => true,
                'requires_document'  => false,
                'placeholder'        => 'e.g. Bangladeshi',
                'helper_text'        => null,
                'options'            => null,
                'sort_order'         => 3,
            ],
            [
                'field_key'          => 'address',
                'label'              => 'Permanent Address',
                'section'            => 'personal',
                'field_type'         => 'textarea',
                'is_required'        => true,
                'requires_document'  => false,
                'placeholder'        => 'House no, Road, City, District',
                'helper_text'        => null,
                'options'            => null,
                'sort_order'         => 4,
            ],
            [
                'field_key'          => 'passport_number',
                'label'              => 'Passport Number',
                'section'            => 'personal',
                'field_type'         => 'text',
                'is_required'        => true,
                'requires_document'  => true,
                'placeholder'        => 'e.g. BA0123456',
                'helper_text'        => 'Upload clear scan of all pages including bio-data page.',
                'options'            => null,
                'sort_order'         => 5,
            ],
            [
                'field_key'          => 'passport_expiry',
                'label'              => 'Passport Expiry Date',
                'section'            => 'personal',
                'field_type'         => 'date',
                'is_required'        => true,
                'requires_document'  => false,
                'placeholder'        => null,
                'helper_text'        => 'Passport must be valid for at least 2 years from intended entry date.',
                'options'            => null,
                'sort_order'         => 6,
            ],

            // ── Academic ─────────────────────────────────────────────────────
            [
                'field_key'          => 'last_qualification',
                'label'              => 'Highest Qualification',
                'section'            => 'academic',
                'field_type'         => 'select',
                'is_required'        => true,
                'requires_document'  => false,
                'placeholder'        => 'Select qualification',
                'helper_text'        => 'Minimum HSC/equivalent required for Japan language schools.',
                'options'            => ['SSC', 'HSC', 'Diploma', 'Bachelor', 'Masters', 'PhD'],
                'sort_order'         => 10,
            ],
            [
                'field_key'          => 'institution_name',
                'label'              => 'Institution / School Name',
                'section'            => 'academic',
                'field_type'         => 'text',
                'is_required'        => true,
                'requires_document'  => false,
                'placeholder'        => 'e.g. Dhaka College',
                'helper_text'        => null,
                'options'            => null,
                'sort_order'         => 11,
            ],
            [
                'field_key'          => 'board_university',
                'label'              => 'Board / University',
                'section'            => 'academic',
                'field_type'         => 'text',
                'is_required'        => true,
                'requires_document'  => false,
                'placeholder'        => 'e.g. Dhaka Education Board / University of Dhaka',
                'helper_text'        => null,
                'options'            => null,
                'sort_order'         => 12,
            ],
            [
                'field_key'          => 'gpa_grade',
                'label'              => 'GPA / Grade / Marks',
                'section'            => 'academic',
                'field_type'         => 'text',
                'is_required'        => true,
                'requires_document'  => true,
                'placeholder'        => 'e.g. GPA 4.50 / A+ / 82%',
                'helper_text'        => 'Upload academic certificate and marksheet.',
                'options'            => null,
                'sort_order'         => 13,
            ],
            [
                'field_key'          => 'passing_year',
                'label'              => 'Year of Passing',
                'section'            => 'academic',
                'field_type'         => 'number',
                'is_required'        => true,
                'requires_document'  => false,
                'placeholder'        => 'e.g. 2022',
                'helper_text'        => null,
                'options'            => null,
                'sort_order'         => 14,
            ],

            // ── Language ─────────────────────────────────────────────────────
            [
                'field_key'          => 'jlpt_level',
                'label'              => 'JLPT Level',
                'section'            => 'language',
                'field_type'         => 'select',
                'is_required'        => true,
                'requires_document'  => true,
                'placeholder'        => 'Select JLPT level',
                'helper_text'        => 'Upload JLPT result certificate if passed. N4 or above preferred for most schools.',
                'options'            => ['N1', 'N2', 'N3', 'N4', 'N5', 'None', 'Preparing'],
                'sort_order'         => 20,
            ],
            [
                'field_key'          => 'jlpt_score',
                'label'              => 'JLPT Score',
                'section'            => 'language',
                'field_type'         => 'text',
                'is_required'        => false,
                'requires_document'  => false,
                'placeholder'        => 'e.g. 108/180',
                'helper_text'        => 'Leave blank if not yet taken.',
                'options'            => null,
                'sort_order'         => 21,
            ],
            [
                'field_key'          => 'jlpt_exam_date',
                'label'              => 'JLPT Exam Date',
                'section'            => 'language',
                'field_type'         => 'date',
                'is_required'        => false,
                'requires_document'  => false,
                'placeholder'        => null,
                'helper_text'        => 'Date you appeared or plan to appear for JLPT.',
                'options'            => null,
                'sort_order'         => 22,
            ],
            [
                'field_key'          => 'custom_japanese_study_duration',
                'label'              => 'Japanese Study Duration',
                'section'            => 'language',
                'field_type'         => 'select',
                'is_required'        => true,
                'requires_document'  => false,
                'placeholder'        => 'How long have you studied Japanese?',
                'helper_text'        => 'Include self-study, coaching, or school.',
                'options'            => ['Less than 3 months', '3–6 months', '6–12 months', '1–2 years', 'More than 2 years'],
                'sort_order'         => 23,
            ],

            // ── Study Goals ───────────────────────────────────────────────────
            [
                'field_key'          => 'target_intake',
                'label'              => 'Target Intake',
                'section'            => 'study',
                'field_type'         => 'select',
                'is_required'        => true,
                'requires_document'  => false,
                'placeholder'        => 'Select intake period',
                'helper_text'        => 'Japan has two main intakes: April and October.',
                'options'            => ['April 2025', 'October 2025', 'April 2026', 'October 2026'],
                'sort_order'         => 30,
            ],
            [
                'field_key'          => 'custom_school_type',
                'label'              => 'School / Program Type',
                'section'            => 'study',
                'field_type'         => 'select',
                'is_required'        => true,
                'requires_document'  => false,
                'placeholder'        => 'Select program type',
                'helper_text'        => 'Language school is most common entry point for Bangladeshi students.',
                'options'            => ['Language School', 'Vocational School (Senmon Gakko)', 'University (Daigaku)', 'Graduate School'],
                'sort_order'         => 31,
            ],
            [
                'field_key'          => 'preferred_institution',
                'label'              => 'Preferred School / University',
                'section'            => 'study',
                'field_type'         => 'text',
                'is_required'        => false,
                'requires_document'  => false,
                'placeholder'        => 'e.g. Tokyo Japanese Language School',
                'helper_text'        => 'Leave blank if not decided yet.',
                'options'            => null,
                'sort_order'         => 32,
            ],
            [
                'field_key'          => 'target_course',
                'label'              => 'Course / Major',
                'section'            => 'study',
                'field_type'         => 'text',
                'is_required'        => false,
                'requires_document'  => false,
                'placeholder'        => 'e.g. Japanese Language, IT, Business Management',
                'helper_text'        => null,
                'options'            => null,
                'sort_order'         => 33,
            ],
            [
                'field_key'          => 'custom_coe_status',
                'label'              => 'CoE Status (Certificate of Eligibility)',
                'section'            => 'study',
                'field_type'         => 'select',
                'is_required'        => false,
                'requires_document'  => true,
                'placeholder'        => 'Select CoE status',
                'helper_text'        => 'CoE is issued by Japan Immigration. Upload copy if already received.',
                'options'            => ['Not Applied Yet', 'Applied — Awaiting', 'Received'],
                'sort_order'         => 34,
            ],

            // ── Sponsor ───────────────────────────────────────────────────────
            [
                'field_key'          => 'sponsor_name',
                'label'              => 'Sponsor Full Name',
                'section'            => 'sponsor',
                'field_type'         => 'text',
                'is_required'        => true,
                'requires_document'  => false,
                'placeholder'        => 'Full legal name of financial sponsor',
                'helper_text'        => "Japan Embassy requires proof of sponsor's financial capacity.",
                'options'            => null,
                'sort_order'         => 40,
            ],
            [
                'field_key'          => 'sponsor_relationship',
                'label'              => 'Relationship to Student',
                'section'            => 'sponsor',
                'field_type'         => 'select',
                'is_required'        => true,
                'requires_document'  => false,
                'placeholder'        => 'Select relationship',
                'helper_text'        => null,
                'options'            => ['Father', 'Mother', 'Spouse', 'Sibling', 'Self', 'Relative', 'Other'],
                'sort_order'         => 41,
            ],
            [
                'field_key'          => 'sponsor_occupation',
                'label'              => 'Sponsor Occupation',
                'section'            => 'sponsor',
                'field_type'         => 'text',
                'is_required'        => true,
                'requires_document'  => true,
                'placeholder'        => 'e.g. Business Owner, Govt. Employee, Doctor',
                'helper_text'        => 'Upload job certificate or business registration document.',
                'options'            => null,
                'sort_order'         => 42,
            ],
            [
                'field_key'          => 'sponsor_monthly_income',
                'label'              => 'Sponsor Monthly Income',
                'section'            => 'sponsor',
                'field_type'         => 'text',
                'is_required'        => true,
                'requires_document'  => true,
                'placeholder'        => 'e.g. BDT 80,000 / JPY 300,000',
                'helper_text'        => 'Upload last 6 months bank statement. Minimum ~BDT 50,000/month recommended.',
                'options'            => null,
                'sort_order'         => 43,
            ],
        ];

        foreach ($fields as $data) {
            FormTemplateField::create(array_merge($data, [
                'form_template_id' => $template->id,
            ]));
        }

        $this->command->info('Japan form template seeded successfully — ' . count($fields) . ' fields created.');
    }
}
